[package]
name = "bevy-boids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
bevy_egui = "0.27.1"
egui_plot = "0.27.2"
rand = "0.8.5"
